### PR TITLE
Temporarily expose err_no to ruby

### PR DESCRIPTION
**Pull request by alexsnaps**
The idea is figure out what causes the spurious failures in monitoring the `cpu_time`

### CODE REVIEW

**Comment by sgnr** [comment]
Oh interesting failure on CI.

**Comment by alexsnaps** [comment]
Ah! Obviously if I don't change the test to match the new behaviour... this won't work. Interesting it failed on CI already (I mean querying the cpu_time for the thread... couldn't get to reproduce this on my VM)

**Comment by alexsnaps** [comment]
@mlhamel care to have a look ?

**Comment by alexsnaps** [comment]
Right, trying to figure out why we can't monitor some times... Could be `-2` or `-3` as well (or even `-1` but I'd be blown away by that!)

**Pull request merged**
